version: '3'

services:
  php:
    container_name: sf_docker_php
    build:
      context: ./.docker/php-fpm
    image: php:7.3-fpm-c
    ports:
      - 9000:9000
    volumes:
      - ./:/var/www/html
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    networks:
      - sf_docker_network
    depends_on:
      - mysql

  nginx:
    container_name: sf_docker_nginx
    build:
      context: ./.docker/nginx
    image: nginx:latest
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www/html
#      - ..:/var/www
#      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
#      - ./nginx/sites/:/etc/nginx/sites-available
#      - ./nginx/conf.d/:/etc/nginx/conf.d
    networks:
      - sf_docker_network
    depends_on:
      - php


  mysql:
    container_name: sf_docker_database
    #restart: always
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3310:3306
    volumes:
      - ./mysql_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    networks:
      - sf_docker_network

networks:
  sf_docker_network:
    driver: bridge
volumes:
  db_sf_docker: {}
